
# Makefile for RISC-V/RV64G

CC      = riscv64-unknown-linux-gnu-gcc
OBJDUMP = riscv64-unknown-linux-gnu-objdump

CFLAGS  += -g -march=rv64g		# without rv64c (compact instruction)
ASFLAGS += -g
LDFLAGS += -static


include ../../../Makefile
